create table
  public.catalog (
    catalog_id integer generated by default as identity,
    sku text null,
    name text null,
    quantity integer null,
    price integer null,
    potion_type integer[] null,
    constraint catalog_pkey primary key (catalog_id)
  ) tablespace pg_default;

create table
  public.cart (
    cart_id integer generated by default as identity,
    str text null,
    constraint cart_pkey primary key (cart_id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    cart_id integer generated by default as identity,
    catalog_id integer null,
    quantity integer null,
    constraint carts_pkey primary key (cart_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references cart (cart_id),
    constraint cart_items_catalog_id_fkey foreign key (catalog_id) references catalog (catalog_id)
  ) tablespace pg_default;

  create table
  public.global_inventory (
    num_red_ml integer null,
    gold integer null,
    num_blue_ml integer null,
    num_green_ml integer null,
    id integer generated by default as identity,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;